# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image as the base for building the application
FROM node:22-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy root + workspace package manifests to install dependencies
COPY package.json package-lock.json ./
COPY apps/firecrawl-mcp/package.json apps/firecrawl-mcp/package.json
COPY apps/firecrawl-cli/package.json apps/firecrawl-cli/package.json
COPY libs/firecrawl-core/package.json libs/firecrawl-core/package.json

# Install dependencies (ignoring scripts to prevent running the prepare script)
RUN npm ci --include=dev --ignore-scripts

# Copy the rest of the application source code
COPY . .

# Build the application using TypeScript
RUN npm run build

# Use a smaller Node.js image for the final image
FROM node:22-slim AS release

# Set the working directory inside the container
WORKDIR /app

# Copy the built application from the builder stage (MCP only)
COPY --from=builder /app/apps/firecrawl-mcp/dist /app/apps/firecrawl-mcp/dist
COPY --from=builder /app/apps/firecrawl-mcp/package.json /app/apps/firecrawl-mcp/package.json
COPY --from=builder /app/apps/firecrawl-cli/package.json /app/apps/firecrawl-cli/package.json
COPY --from=builder /app/libs/firecrawl-core/package.json /app/libs/firecrawl-core/package.json
COPY --from=builder /app/package.json /app/package.json
COPY --from=builder /app/package-lock.json /app/package-lock.json

# Install only production dependencies
RUN npm ci --omit=dev --ignore-scripts

# Set environment variables for API key and custom API URL if needed


# Specify the command to run the application
ENTRYPOINT ["node", "apps/firecrawl-mcp/dist/mcp.js"]
